react-native-masked-view/masked-view

package.json
react-native-masked-view.podspec

Since react 0.60 is around the corner, we should add podspec file so that automatic linking for iOS works properly

Add .podspec file

---

RNCMaskedView.podspec

Run `pod install` after linking (`react-native link @react-native-community/masked-view`) package caused next error:

Fix pod file (name and git tag)

---

android/src/main/java/org/reactnative/maskedview/RNCMaskedViewManager.java

Remove unused Nullable import from Android Support Library, that cause build failures on React Native 0.60+
| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

remove unused android support library import

---

package.json

Currently when installing `@react-native-community/masked-view` with the latest version of RN yarn prints following warning:
> @react-native-community/masked-view@0.1.5" has incorrect peer dependency "react-native@^0.57".
Changing `^` to `>=` in RN version string fixes that issue (the correct version string is also used in `devDependencies`).

fix "incorrect peer dependency" warning

---

android/src/main/java/org/reactnative/maskedview/RNCMaskedView.java

This allows for masking contents with transparent backgrounds. Previously the mask would be drawn under the content, because it was the child at index 0. This caused it to show through when the content was transparent, which has different behaviour than iOS had.
To do this, we simply set the alpha of the view to 1 before drawing the mask bitmap and than set it to 0 afterwards.
| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

fix(android): Ensure the mask view is not drawn

---

android/src/main/java/org/reactnative/maskedview/RNCMaskedView.java

I ran into the same issues as some others with an animated `maskElement` on Android, 
https://github.com/react-native-community/react-native-masked-view/issues/22. The bitmap used for masking was drawn on layout, and then cached for future drawing. I changed this to always draw the mask element before applying the mask on the underlying view. 
I am far from an expert on Android development and this might be a bad pattern, but redrawing the bitmap for the mask element on each drawing cycle seems to be performant for me.  
Use an `Animated.View` as a mask element.
Perform an animation and see that the mask is applied correctly
| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |
- [x ] I have tested this on a device and a simulator

Redraw mask element on each dispatchDraw

---

package.json

When I download `@react-native-community/masked-view`, unnecessary files such as `img` folder and config files are included in the `node_modules`.
By specifying `files` in package.json, it will only download the necessary files to use the masked-view
getting only the required files to run masked view on `npm install` and `yarn install`

chore: specify files in package.json

---

README.md

We've been recommending devs use `npx pod-install` since it will attempt to install CocoaPods CLI if it's not available on the computer (cite [React Navigation setup guide](https://reactnavigation.org/docs/getting-started/#installing-dependencies-into-a-bare-react-native-project)). This has proved very useful for Expo users who are now migrating to the bare workflow and want to use community packages in their projects.

Recommend npx pod-install for setup instructions

---

RNCMaskedView.podspec

The latest Xcode 12 fails to build when a module does not depend on `React-Core` directly. This change is necessary for all native modules on iOS. For details please see: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
1. Build an App with Xcode 11.x. Result: The app builds.
2. Build an App with Xcode 12. Result: The app will not build when depending on `React`.
3. Build an App with Xcode 12 with the PR changes applied. Result: The app builds.
Mac OS with Xcode 12
see Test Plan
| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

fix: Xcode 12 compatibility

---

README.md
RNCMaskedView.podspec
package.json
types/index.d.ts

Migrating to @react-native-masked-view namespace to migrate out of react-native-community namespace, as stated in react-native-community/discussions-and-proposals#176

chore: move to react-native-masked-view namespace

---

README.md

It seems this library [is supported by Expo's managed workflow](https://docs.expo.io/versions/latest/sdk/masked-view/) so I removed the warning.

Removed note about lack of Expo support

---

android/src/main/java/org/reactnative/maskedview/RNCMaskedView.java

I ran into the same problems as others with low FPS on Android, https://github.com/react-native-masked-view/masked-view/issues/88 and https://github.com/react-native-masked-view/masked-view/issues/93. 
Instead of naively redrawing the mask element on each draw this invalidates the stored bitmap when the mask element is invalidated. I believe this fixes unnecessary redraws for mask elements while still supporting animated mask elements. Basically this is an improvement on the previous fix here:  
Use mask element on Android and you should see 60 fps.

Only redraw bitmap for mask element when invalidated

---

android/src/main/java/org/reactnative/maskedview/RNCMaskedView.java

When including a masked-view in one route (using a library like [react navigation](https://reactnavigation.org/)), and the user navigates to a new route on the stack and presses the back button, the masked-view will not rerender any more.
The problem is that the bitmap invalidation does not happen when the view is attached to the window. Causing calls of React native to `dispatchDraw` to not actually draw, keeping this component in a permanent state of `mBitmapMaskInvalidated = false;`

fix: Fixing bug that made masked view unresponsive after re-attaching

---

android/src/main/java/org/reactnative/maskedview/RNCMaskedView.java

We were having a lot of issues with performance on android such as explained in #110 but also some other users are facing in #88. By enabling hardware acceleration (default is set to software and results in extremely poor performance) for the Android Canvas we managed to solve these issues entirely. The project ran at 60fps, similar to IOS.
Here is a video showing software and hardware in action:
[Hardware Acceleration OFF](https://www.dropbox.com/s/tp92z4mhwgje2t6/software.webm?dl=0) - performance is so bad it's impacting the recording, sorry.
[Hardware Acceleration ON](https://www.dropbox.com/s/7hc0enqmitf0ijh/hardware.webm?dl=0)
When lots of re-renders are happening to a screen, the default code has extremely poor performance (as seen in the video). You can test this by creating a …

Performance fix for Android by enabling hardware acceleration

---

README.md
android/src/main/java/org/reactnative/maskedview/RNCMaskedView.java
android/src/main/java/org/reactnative/maskedview/RNCMaskedViewManager.java
js/MaskedViewTypes.js
types/index.d.ts

#116 improved performance, but disabled the ability to animate the mask on Android. This PR introduces a new property `androidRenderingMode` which allows the user to choose the rendering mode should they require the ability to animate the mask element and are willing to accept the performance trade-off.
Ideally a way to animate the mask while keeping performance good can be found, but until then this seems like a reasonable compromise.
Fixes #117

Allow Android rendering mode (hardware/software) to be controlled via a prop

---

README.md

The terminal commands that were in README.md, such as `$ yarn add @react-native-masked-view/masked-view
` started with `$`, but this symbol was also copied with GitHub's copy

Remove $ from README.md terminal commands

---

.flowconfig
js/MaskedViewTypes.js

Fixes #168 
Remove deprecated ViewPropTypes and replaced it with Flow Type provided by react-native
flow passes

Remove deprecated ViewPropTypes

---

android/src/main/java/org/reactnative/maskedview/RNCMaskedView.java

This PR fixes an issue many users have been experiencing on Android when navigating back from one screen to the other.
Closes https://github.com/react-native-masked-view/masked-view/issues/160 
1. On Android navigate to a screen with a component that users MaskedView
2. Navigate back using the hardware button 
3. Observe the Mask no longer being removed before the screen is fully hidden 
After 
https://user-images.githubusercontent.com/11707729/191022838-5814bc6d-5c9d-4d5c-a168-d9a4ecf05367.mov
Before
https://user-images.githubusercontent.com/11707729/191020488-acc1b917-6ea4-4238-96f7-47f177a52f40.mov

fix: Mask flicker while navigating on Android

---

types/index.d.ts

Updating to react native 0.71, TypeScript errors on this library. The utility type `Constructor` is private in latest typings. Using this export degrades to `any` type.
`JSX element class does not support attributes because it does not have a 'props' property.`
`npx tsc` runs clean after making this change on a RN 0.71 app.

fix(types): utility type removed from RN 0.71

---

.github/workflows/ci.yml

Due to deprecation of `save-state` and `set-output` commands in GitHub Action workflows, this PR should prevent workflows to fail after the 31st May 2023.
Link to GitHub blogg:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

fix: deprecated set-output in GitHub Action workflows

---

android/build.gradle
android/src/main/AndroidManifest.xml

In [prev-PR](https://github.com/react-native-masked-view/masked-view/pull/195), i remove package from AndroidManifest.xml file, it drop support for RN <0.71. 
Now, I check ANDROID_GRADLE_PLUGIN_VERSION to use namespace and remove package in AndroidManifest.xml file

feat(all): add support  RN <0.71 when add namespace

---

android/src/main/java/org/reactnative/maskedview/RNCMaskedView.java

This pull request adds an `invalidate()` call to `RNCMaskedView.onDescendantInvalidated`
This addresses the following issue: sometimes, the MaskedView would display a stale content even though React re-render happened in one of the children
As far as I understand, the issue was happening because in `RNCMaskedView.dispatchDraw` we would render the content of the masked view into an off-screen buffer ([link](https://developer.android.com/topic/performance/hardware-accel#layers)) *before* the children would have been re-drawn ([link](https://developer.android.com/reference/android/view/View#dispatchDraw(android.graphics.Canvas))), and later the offscreen buffer would be used by the hardware rendering even though it contains a stale snapshot of the children.
A simple solution is to invalidate …

Calling invalidate in RNCMaskedView

---

README.md
js/MaskedView.web.js

This approach uses `moden-screenshot` package for snapshoting the mask element.
then we put the image as a mask by new CSS mask api.
**Note**: I did not check if this method aligns with native versions.

Initial Web support
